In [2]:
# import necessary libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import joblib
import warnings
warnings.filterwarnings("ignore")

In [3]:
# create datasets, evaluation_results_json, models_joblib folders if they don't exist already
if not os.path.exists('datasets'):
    os.makedirs('datasets')
if not os.path.exists('evaluation_results_json'):
    os.makedirs('evaluation_results_json')
if not os.path.exists('models_joblib'):
    os.makedirs('models_joblib')

In [4]:
df_cip = pd.read_csv("Resources/ciprofloxacin.csv")
df_cip.head()

patient_id  date_admission ciprofloxacin     sex  age
0        7923               3             S  female   42
1        7923               2             S  female   42
2        7923               1             S  female   42
3        7825               1             S  female   21
4        5375               2             S    male   65

In [5]:
# drop patient_id column
df_cip = df_cip.drop(columns=['patient_id'])
df_cip.head()

date_admission ciprofloxacin     sex  age
0               3             S  female   42
1               2             S  female   42
2               1             S  female   42
3               1             S  female   21
4               2             S    male   65

In [6]:
# in ciprofloxacin column replace S is 0 and R is 1 
df_cip['ciprofloxacin'] = df_cip['ciprofloxacin'].replace({'S': 0, 'R': 1})
df_cip.head()

date_admission  ciprofloxacin     sex  age
0               3              0  female   42
1               2              0  female   42
2               1              0  female   42
3               1              0  female   21
4               2              0    male   65

In [7]:
df_cip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   date_admission  10108 non-null  int64 
 1   ciprofloxacin   10108 non-null  int64 
 2   sex             10108 non-null  object
 3   age             10108 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 316.0+ KB


In [8]:
df_gen = pd.read_csv("Resources/gentamicin.csv")
df_gen.head()

patient_id  date_admission gentamicin     sex  age
0        7923               3          S  female   42
1        7923               2          R  female   42
2        7923               1          S  female   42
3        7825               1          S  female   21
4        5375               2          R    male   65

In [9]:
# drop patient_id column 
df_gen = df_gen.drop(columns=['patient_id'])
df_gen.head()

date_admission gentamicin     sex  age
0               3          S  female   42
1               2          R  female   42
2               1          S  female   42
3               1          S  female   21
4               2          R    male   65

In [10]:
# in gentamicin column replace S is 0 and R is 1
df_gen['gentamicin'] = df_gen['gentamicin'].replace({'S': 0, 'R': 1})
df_gen.head()

date_admission  gentamicin     sex  age
0               3           0  female   42
1               2           1  female   42
2               1           0  female   42
3               1           0  female   21
4               2           1    male   65

In [11]:
df_gen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   date_admission  10108 non-null  int64 
 1   gentamicin      10108 non-null  int64 
 2   sex             10108 non-null  object
 3   age             10108 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 316.0+ KB


In [12]:
df_omox = pd.read_csv("Resources/amoxicillin_clavulanic_acid.csv")
df_omox.head()

patient_id  date_admission amoxicillin_clavulanic_acid     sex  age
0        7923               3                           S  female   42
1        7923               2                           S  female   42
2        7923               1                           S  female   42
3        7825               1                           R  female   21
4        5375               2                           S    male   65

In [13]:
# drop patient_id column
df_omox = df_omox.drop(columns=['patient_id'])
df_omox.head()

date_admission amoxicillin_clavulanic_acid     sex  age
0               3                           S  female   42
1               2                           S  female   42
2               1                           S  female   42
3               1                           R  female   21
4               2                           S    male   65

In [14]:
# in amoxicillin_clavulanic_acid column replace S is 0 and R is 1
df_omox['amoxicillin_clavulanic_acid'] = df_omox['amoxicillin_clavulanic_acid'].replace({'S': 0, 'R': 1})
df_omox.head()

date_admission  amoxicillin_clavulanic_acid     sex  age
0               3                            0  female   42
1               2                            0  female   42
2               1                            0  female   42
3               1                            1  female   21
4               2                            0    male   65

In [15]:
df_omox.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 4 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   date_admission               10108 non-null  int64 
 1   amoxicillin_clavulanic_acid  10108 non-null  int64 
 2   sex                          10108 non-null  object
 3   age                          10108 non-null  int64 
dtypes: int64(3), object(1)
memory usage: 316.0+ KB


In [16]:
from main import preprocess
preprocess(input_data=df_cip, target='ciprofloxacin', numeric_features=['age'], categorical_features = ['sex'], train_features_output_path='datasets/cip_train_features.csv', train_labels_output_path='datasets/cip_train_labels.csv', val_features_output_path='datasets/cip_val_features.csv', val_labels_output_path='datasets/cip_val_labels.csv', test_features_output_path='datasets/cip_test_features.csv', test_labels_output_path='datasets/cip_test_labels.csv')

In [17]:
preprocess(input_data=df_gen, target='gentamicin', numeric_features=['age'], categorical_features= ['sex'], train_features_output_path='datasets/gen_train_features.csv', train_labels_output_path='datasets/gen_train_labels.csv', val_features_output_path='datasets/gen_val_features.csv', val_labels_output_path='datasets/gen_val_labels.csv', test_features_output_path='datasets/gen_test_features.csv', test_labels_output_path='datasets/gen_test_labels.csv')

In [18]:
preprocess(input_data=df_omox, target='amoxicillin_clavulanic_acid', numeric_features=['age'], categorical_features= ['sex'], train_features_output_path='datasets/omox_train_features.csv', train_labels_output_path='datasets/omox_train_labels.csv', val_features_output_path='datasets/omox_val_features.csv', val_labels_output_path='datasets/omox_val_labels.csv', test_features_output_path='datasets/omox_test_features.csv', test_labels_output_path='datasets/omox_test_labels.csv')

In [19]:
from main import training_lr
training_lr(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_lr_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_lr_model.joblib


In [20]:
training_lr(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_lr_model.joblib')

Validation Set Metrics
Accuracy: 0.8331273176761433
Precision: 0.8507295173961841
Recall: 0.846927374301676
F1 Score: 0.8488241881298992
ROC AUC: 0.8314858171646692
Confusion Matrix: 
[[590 133]
 [137 758]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.81      0.82      0.81       723
           1       0.85      0.85      0.85       895

    accuracy                           0.83      1618
   macro avg       0.83      0.83      0.83      1618
weighted avg       0.83      0.83      0.83      1618

Training Accuracy: 0.819882498453927
Validation Accuracy: 0.8331273176761433
Saving model to models_joblib/gen_lr_model.joblib


In [21]:
training_lr(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_lr_model.joblib')

Validation Set Metrics
Accuracy: 0.8479604449938195
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1372    0]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8479604449938195
Saving model to models_joblib/omox_lr_model.joblib


In [22]:
from main import evaluation_lr
evaluation_lr(model_path='models_joblib/cip_lr_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_lr_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



({'classification_metrics': {'accuracy': {'value': 0.8986152324431256},
   'precision': {'value': 0.0},
   'recall': {'value': 0.0},
   'f1': {'value': 0.0},
   'roc_auc': {'value': 0.5}}},
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [23]:
evaluation_lr(model_path='models_joblib/gen_lr_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_lr_evaluation.json')

Test Set Metrics
Accuracy: 0.8372898120672602
Precision: 0.8563922942206655
Recall: 0.8556430446194225
F1 Score: 0.8560175054704595
ROC AUC: 0.8345336952334884
Confusion Matrix: 
[[715 164]
 [165 978]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.81      0.81      0.81       879
           1       0.86      0.86      0.86      1143

    accuracy                           0.84      2022
   macro avg       0.83      0.83      0.83      2022
weighted avg       0.84      0.84      0.84      2022



({'classification_metrics': {'accuracy': {'value': 0.8372898120672602},
   'precision': {'value': 0.8563922942206655},
   'recall': {'value': 0.8556430446194225},
   'f1': {'value': 0.8560175054704595},
   'roc_auc': {'value': 0.8345336952334884}}},
 array([1, 1, 0, ..., 1, 1, 1], dtype=int64))

In [24]:
evaluation_lr(model_path='models_joblib/omox_lr_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_lr_evaluation.json')

Test Set Metrics


Accuracy: 0.8422354104846687
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1703    0]
 [ 319    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.00      0.00      0.00       319

    accuracy                           0.84      2022
   macro avg       0.42      0.50      0.46      2022
weighted avg       0.71      0.84      0.77      2022



({'classification_metrics': {'accuracy': {'value': 0.8422354104846687},
   'precision': {'value': 0.0},
   'recall': {'value': 0.0},
   'f1': {'value': 0.0},
   'roc_auc': {'value': 0.5}}},
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [25]:
from main import training_dtc
training_dtc(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_dtc_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_dtc_model.joblib


In [26]:
training_dtc(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_dtc_model.joblib')

Validation Set Metrics
Accuracy: 0.8572311495673671
Precision: 0.9311688311688312
Recall: 0.8011173184357542
F1 Score: 0.8612612612612612
ROC AUC: 0.863905823809855
Confusion Matrix: 
[[670  53]
 [178 717]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.93      0.85       723
           1       0.93      0.80      0.86       895

    accuracy                           0.86      1618
   macro avg       0.86      0.86      0.86      1618
weighted avg       0.87      0.86      0.86      1618

Training Accuracy: 0.845856524427953
Validation Accuracy: 0.8572311495673671
Saving model to models_joblib/gen_dtc_model.joblib


In [27]:
training_dtc(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_dtc_model.joblib')

Validation Set Metrics


Accuracy: 0.8479604449938195
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1372    0]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8479604449938195
Saving model to models_joblib/omox_dtc_model.joblib


In [28]:
from main import training_knn
training_knn(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_knn_model.joblib')

Validation Set Metrics
Accuracy: 0.8899876390605687
Precision: 0.12
Recall: 0.018867924528301886
F1 Score: 0.03260869565217391
ROC AUC: 0.5018945517089761
Confusion Matrix: 
[[1437   22]
 [ 156    3]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      0.98      0.94      1459
           1       0.12      0.02      0.03       159

    accuracy                           0.89      1618
   macro avg       0.51      0.50      0.49      1618
weighted avg       0.83      0.89      0.85      1618

Training Accuracy: 0.8910018552875696
Validation Accuracy: 0.8899876390605687
Saving model to models_joblib/cip_knn_model.joblib


In [29]:
training_knn(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_knn_model.joblib')

Validation Set Metrics
Accuracy: 0.826946847960445
Precision: 0.8763769889840881
Recall: 0.8
F1 Score: 0.8364485981308412
ROC AUC: 0.83015214384509
Confusion Matrix: 
[[622 101]
 [179 716]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.86      0.82       723
           1       0.88      0.80      0.84       895

    accuracy                           0.83      1618
   macro avg       0.83      0.83      0.83      1618
weighted avg       0.83      0.83      0.83      1618

Training Accuracy: 0.826530612244898
Validation Accuracy: 0.826946847960445
Saving model to models_joblib/gen_knn_model.joblib


In [30]:
training_knn(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_knn_model.joblib')

Validation Set Metrics
Accuracy: 0.8405438813349815
Precision: 0.16666666666666666
Recall: 0.012195121951219513
F1 Score: 0.022727272727272724
ROC AUC: 0.5006310886724028
Confusion Matrix: 
[[1357   15]
 [ 243    3]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      1372
           1       0.17      0.01      0.02       246

    accuracy                           0.84      1618
   macro avg       0.51      0.50      0.47      1618
weighted avg       0.74      0.84      0.78      1618

Training Accuracy: 0.8503401360544217
Validation Accuracy: 0.8405438813349815
Saving model to models_joblib/omox_knn_model.joblib


In [31]:
from main import training_rfc
training_rfc(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_rfc_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_rfc_model.joblib


In [32]:
training_rfc(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_rfc_model.joblib')

Validation Set Metrics
Accuracy: 0.8566131025957973
Precision: 0.9288486416558862
Recall: 0.8022346368715084
F1 Score: 0.8609112709832135
ROC AUC: 0.8630813571632784
Confusion Matrix: 
[[668  55]
 [177 718]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       723
           1       0.93      0.80      0.86       895

    accuracy                           0.86      1618
   macro avg       0.86      0.86      0.86      1618
weighted avg       0.87      0.86      0.86      1618

Training Accuracy: 0.845856524427953
Validation Accuracy: 0.8566131025957973
Saving model to models_joblib/gen_rfc_model.joblib


In [33]:
training_rfc(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_rfc_model.joblib')

Validation Set Metrics
Accuracy: 0.8467243510506799
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.49927113702623904
Confusion Matrix: 
[[1370    2]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8467243510506799
Saving model to models_joblib/omox_rfc_model.joblib


In [34]:
from main import training_gbc
training_gbc(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_gbc_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_gbc_model.joblib


In [35]:
training_gbc(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_gbc_model.joblib')

Validation Set Metrics
Accuracy: 0.8572311495673671
Precision: 0.9300518134715026
Recall: 0.8022346368715084
F1 Score: 0.8614277144571085
ROC AUC: 0.8637729200955052
Confusion Matrix: 
[[669  54]
 [177 718]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.93      0.85       723
           1       0.93      0.80      0.86       895

    accuracy                           0.86      1618
   macro avg       0.86      0.86      0.86      1618
weighted avg       0.87      0.86      0.86      1618

Training Accuracy: 0.8432282003710575
Validation Accuracy: 0.8572311495673671
Saving model to models_joblib/gen_gbc_model.joblib


In [36]:
training_gbc(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_gbc_model.joblib')

Validation Set Metrics
Accuracy: 0.8479604449938195
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1372    0]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8479604449938195
Saving model to models_joblib/omox_gbc_model.joblib


In [37]:
from main import training_bc
training_bc(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_bc_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_bc_model.joblib


In [38]:
training_bc(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_bc_model.joblib')

Validation Set Metrics
Accuracy: 0.8547589616810878
Precision: 0.927461139896373
Recall: 0.8
F1 Score: 0.8590281943611278
ROC AUC: 0.8612724757952974
Confusion Matrix: 
[[667  56]
 [179 716]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       723
           1       0.93      0.80      0.86       895

    accuracy                           0.85      1618
   macro avg       0.86      0.86      0.85      1618
weighted avg       0.87      0.85      0.86      1618

Training Accuracy: 0.8453927025355596
Validation Accuracy: 0.8547589616810878
Saving model to models_joblib/gen_bc_model.joblib


In [39]:
training_bc(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_bc_model.joblib')

Validation Set Metrics
Accuracy: 0.8467243510506799
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.49927113702623904
Confusion Matrix: 
[[1370    2]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8467243510506799
Saving model to models_joblib/omox_bc_model.joblib


In [40]:
from main import training_abc
training_abc(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_abc_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_abc_model.joblib


In [41]:
training_abc(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_abc_model.joblib')

Validation Set Metrics
Accuracy: 0.8572311495673671
Precision: 0.9300518134715026
Recall: 0.8022346368715084
F1 Score: 0.8614277144571085
ROC AUC: 0.8637729200955052
Confusion Matrix: 
[[669  54]
 [177 718]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.93      0.85       723
           1       0.93      0.80      0.86       895

    accuracy                           0.86      1618
   macro avg       0.86      0.86      0.86      1618
weighted avg       0.87      0.86      0.86      1618

Training Accuracy: 0.8432282003710575
Validation Accuracy: 0.8572311495673671
Saving model to models_joblib/gen_abc_model.joblib


In [42]:
training_abc(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_abc_model.joblib')

Validation Set Metrics
Accuracy: 0.8479604449938195
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1372    0]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8479604449938195
Saving model to models_joblib/omox_abc_model.joblib


In [43]:
from main import training_xgbc
training_xgbc(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_xgbc_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_xgbc_model.joblib


In [44]:
training_xgbc(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_xgbc_model.joblib')

Validation Set Metrics
Accuracy: 0.8572311495673671
Precision: 0.9322916666666666
Recall: 0.8
F1 Score: 0.8610944076969332
ROC AUC: 0.8640387275242047
Confusion Matrix: 
[[671  52]
 [179 716]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.93      0.85       723
           1       0.93      0.80      0.86       895

    accuracy                           0.86      1618
   macro avg       0.86      0.86      0.86      1618
weighted avg       0.87      0.86      0.86      1618

Training Accuracy: 0.8457019171304886
Validation Accuracy: 0.8572311495673671
Saving model to models_joblib/gen_xgbc_model.joblib


In [45]:
training_xgbc(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_xgbc_model.joblib')

Validation Set Metrics
Accuracy: 0.8479604449938195
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1372    0]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8479604449938195
Saving model to models_joblib/omox_xgbc_model.joblib


In [46]:
from main import training_svc
training_svc(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_svc_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_svc_model.joblib


In [47]:
training_svc(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_svc_model.joblib')

Validation Set Metrics
Accuracy: 0.8547589616810878
Precision: 0.9423592493297587
Recall: 0.7854748603351955
F1 Score: 0.8567946374162096
ROC AUC: 0.863000224081844
Confusion Matrix: 
[[680  43]
 [192 703]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.94      0.85       723
           1       0.94      0.79      0.86       895

    accuracy                           0.85      1618
   macro avg       0.86      0.86      0.85      1618
weighted avg       0.87      0.85      0.85      1618

Training Accuracy: 0.8409090909090909
Validation Accuracy: 0.8547589616810878
Saving model to models_joblib/gen_svc_model.joblib


In [48]:
training_svc(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_svc_model.joblib')

Validation Set Metrics
Accuracy: 0.8479604449938195
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1372    0]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8479604449938195
Saving model to models_joblib/omox_svc_model.joblib


In [49]:
from main import training_nb
training_nb(train_features_data='datasets/cip_train_features.csv', train_labels_data='datasets/cip_train_labels.csv', val_features_data='datasets/cip_val_features.csv', val_labels_data='datasets/cip_val_labels.csv', model_output_directory='models_joblib/cip_nb_model.joblib')

Validation Set Metrics
Accuracy: 0.9017305315203955
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1459    0]
 [ 159    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1459
           1       0.00      0.00      0.00       159

    accuracy                           0.90      1618
   macro avg       0.45      0.50      0.47      1618
weighted avg       0.81      0.90      0.86      1618

Training Accuracy: 0.9013605442176871
Validation Accuracy: 0.9017305315203955
Saving model to models_joblib/cip_nb_model.joblib


In [50]:
training_nb(train_features_data='datasets/gen_train_features.csv', train_labels_data='datasets/gen_train_labels.csv', val_features_data='datasets/gen_val_features.csv', val_labels_data='datasets/gen_val_labels.csv', model_output_directory='models_joblib/gen_nb_model.joblib')

Validation Set Metrics
Accuracy: 0.8393077873918418
Precision: 0.8628571428571429
Recall: 0.8435754189944135
F1 Score: 0.8531073446327684
ROC AUC: 0.8388001576299867
Confusion Matrix: 
[[603 120]
 [140 755]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       723
           1       0.86      0.84      0.85       895

    accuracy                           0.84      1618
   macro avg       0.84      0.84      0.84      1618
weighted avg       0.84      0.84      0.84      1618

Training Accuracy: 0.8239022881880025
Validation Accuracy: 0.8393077873918418
Saving model to models_joblib/gen_nb_model.joblib


In [51]:
training_nb(train_features_data='datasets/omox_train_features.csv', train_labels_data='datasets/omox_train_labels.csv', val_features_data='datasets/omox_val_features.csv', val_labels_data='datasets/omox_val_labels.csv', model_output_directory='models_joblib/omox_nb_model.joblib')

Validation Set Metrics


Accuracy: 0.8479604449938195
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1372    0]
 [ 246    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1372
           1       0.00      0.00      0.00       246

    accuracy                           0.85      1618
   macro avg       0.42      0.50      0.46      1618
weighted avg       0.72      0.85      0.78      1618

Training Accuracy: 0.8583797155225726
Validation Accuracy: 0.8479604449938195
Saving model to models_joblib/omox_nb_model.joblib


In [52]:
from main import evaluation_dtc
evaluation_dtc(model_path='models_joblib/cip_dtc_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_dtc_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [61]:
evaluation_dtc(model_path='models_joblib/gen_dtc_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_dtc_evaluation.json')

Test Set Metrics
Accuracy: 0.8565776458951533
Precision: 0.9392378990731205
Recall: 0.7979002624671916
F1 Score: 0.8628192999053926
ROC AUC: 0.8653892666147107
Confusion Matrix: 
[[820  59]
 [231 912]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.93      0.85       879
           1       0.94      0.80      0.86      1143

    accuracy                           0.86      2022
   macro avg       0.86      0.87      0.86      2022
weighted avg       0.87      0.86      0.86      2022



In [62]:
evaluation_dtc(model_path='models_joblib/omox_dtc_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_dtc_evaluation.json')

Test Set Metrics
Accuracy: 0.8422354104846687
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1703    0]
 [ 319    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.00      0.00      0.00       319

    accuracy                           0.84      2022
   macro avg       0.42      0.50      0.46      2022
weighted avg       0.71      0.84      0.77      2022



In [53]:
from main import evaluation_knn
evaluation_knn(model_path='models_joblib/cip_knn_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_knn_evaluation.json')

Test Set Metrics
Accuracy: 0.8882294757665677
Precision: 0.16129032258064516
Recall: 0.024390243902439025
F1 Score: 0.04237288135593221
ROC AUC: 0.5050404714283797
Confusion Matrix: 
[[1791   26]
 [ 200    5]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      0.99      0.94      1817
           1       0.16      0.02      0.04       205

    accuracy                           0.89      2022
   macro avg       0.53      0.51      0.49      2022
weighted avg       0.82      0.89      0.85      2022



In [63]:
evaluation_knn(model_path='models_joblib/gen_knn_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_knn_evaluation.json')

Test Set Metrics
Accuracy: 0.8367952522255193
Precision: 0.8912415784408084
Recall: 0.8101487314085739
F1 Score: 0.8487626031164069
ROC AUC: 0.8407967775359139
Confusion Matrix: 
[[766 113]
 [217 926]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.87      0.82       879
           1       0.89      0.81      0.85      1143

    accuracy                           0.84      2022
   macro avg       0.84      0.84      0.84      2022
weighted avg       0.84      0.84      0.84      2022



In [64]:
evaluation_knn(model_path='models_joblib/omox_knn_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_knn_evaluation.json')

Test Set Metrics
Accuracy: 0.83135509396637
Precision: 0.19444444444444445
Recall: 0.0219435736677116
F1 Score: 0.039436619718309855
ROC AUC: 0.502457400456874
Confusion Matrix: 
[[1674   29]
 [ 312    7]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      0.98      0.91      1703
           1       0.19      0.02      0.04       319

    accuracy                           0.83      2022
   macro avg       0.52      0.50      0.47      2022
weighted avg       0.74      0.83      0.77      2022



In [54]:
from main import evaluation_rfc
evaluation_rfc(model_path='models_joblib/cip_rfc_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_rfc_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [65]:
evaluation_rfc(model_path='models_joblib/gen_rfc_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_rfc_evaluation.json')

Test Set Metrics
Accuracy: 0.8560830860534124
Precision: 0.9373716632443532
Recall: 0.7987751531058618
F1 Score: 0.8625413320736892
ROC AUC: 0.8646890555062869
Confusion Matrix: 
[[818  61]
 [230 913]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.93      0.85       879
           1       0.94      0.80      0.86      1143

    accuracy                           0.86      2022
   macro avg       0.86      0.86      0.86      2022
weighted avg       0.87      0.86      0.86      2022



In [66]:
evaluation_rfc(model_path='models_joblib/omox_rfc_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_rfc_evaluation.json')

Test Set Metrics
Accuracy: 0.8417408506429278
Precision: 0.3333333333333333
Recall: 0.003134796238244514
F1 Score: 0.006211180124223602
ROC AUC: 0.5009801990586408
Confusion Matrix: 
[[1701    2]
 [ 318    1]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.33      0.00      0.01       319

    accuracy                           0.84      2022
   macro avg       0.59      0.50      0.46      2022
weighted avg       0.76      0.84      0.77      2022



In [55]:
from main import evaluation_gbc
evaluation_gbc(model_path='models_joblib/cip_gbc_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_gbc_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [67]:
evaluation_gbc(model_path='models_joblib/gen_gbc_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_gbc_evaluation.json')

Test Set Metrics
Accuracy: 0.8610286844708209
Precision: 0.9406952965235174
Recall: 0.8048993875765529
F1 Score: 0.8675153229608675
ROC AUC: 0.8694576573832707
Confusion Matrix: 
[[821  58]
 [223 920]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.93      0.85       879
           1       0.94      0.80      0.87      1143

    accuracy                           0.86      2022
   macro avg       0.86      0.87      0.86      2022
weighted avg       0.87      0.86      0.86      2022



In [68]:
evaluation_gbc(model_path='models_joblib/omox_gbc_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_gbc_evaluation.json')

Test Set Metrics
Accuracy: 0.8422354104846687
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1703    0]
 [ 319    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.00      0.00      0.00       319

    accuracy                           0.84      2022
   macro avg       0.42      0.50      0.46      2022
weighted avg       0.71      0.84      0.77      2022



In [56]:
from main import evaluation_bc
evaluation_bc(model_path='models_joblib/cip_bc_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_bc_evaluation.json')

Test Set Metrics


Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [69]:
evaluation_bc(model_path='models_joblib/gen_bc_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_bc_evaluation.json')

Test Set Metrics
Accuracy: 0.8531157270029673
Precision: 0.9360824742268041
Recall: 0.7944006999125109
F1 Score: 0.8594415522953148
ROC AUC: 0.8619330006957322
Confusion Matrix: 
[[817  62]
 [235 908]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.93      0.85       879
           1       0.94      0.79      0.86      1143

    accuracy                           0.85      2022
   macro avg       0.86      0.86      0.85      2022
weighted avg       0.87      0.85      0.85      2022



In [70]:
evaluation_bc(model_path='models_joblib/omox_bc_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_bc_evaluation.json')

Test Set Metrics
Accuracy: 0.8417408506429278
Precision: 0.3333333333333333
Recall: 0.003134796238244514
F1 Score: 0.006211180124223602
ROC AUC: 0.5009801990586408
Confusion Matrix: 
[[1701    2]
 [ 318    1]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.33      0.00      0.01       319

    accuracy                           0.84      2022
   macro avg       0.59      0.50      0.46      2022
weighted avg       0.76      0.84      0.77      2022



In [57]:
from main import evaluation_abc
evaluation_abc(model_path='models_joblib/cip_abc_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_abc_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [71]:
evaluation_abc(model_path='models_joblib/gen_abc_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_abc_evaluation.json')

Test Set Metrics
Accuracy: 0.8610286844708209
Precision: 0.9406952965235174
Recall: 0.8048993875765529
F1 Score: 0.8675153229608675
ROC AUC: 0.8694576573832707
Confusion Matrix: 
[[821  58]
 [223 920]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.93      0.85       879
           1       0.94      0.80      0.87      1143

    accuracy                           0.86      2022
   macro avg       0.86      0.87      0.86      2022
weighted avg       0.87      0.86      0.86      2022



In [72]:
evaluation_abc(model_path='models_joblib/omox_abc_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_abc_evaluation.json')

Test Set Metrics
Accuracy: 0.8422354104846687
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1703    0]
 [ 319    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.00      0.00      0.00       319

    accuracy                           0.84      2022
   macro avg       0.42      0.50      0.46      2022
weighted avg       0.71      0.84      0.77      2022



In [58]:
from main import evaluation_xgbc
evaluation_xgbc(model_path='models_joblib/cip_xgbc_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_xgbc_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [73]:
evaluation_xgbc(model_path='models_joblib/gen_xgbc_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_xgbc_evaluation.json')

Test Set Metrics
Accuracy: 0.8560830860534124
Precision: 0.9373716632443532
Recall: 0.7987751531058618
F1 Score: 0.8625413320736892
ROC AUC: 0.8646890555062869
Confusion Matrix: 
[[818  61]
 [230 913]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.93      0.85       879
           1       0.94      0.80      0.86      1143

    accuracy                           0.86      2022
   macro avg       0.86      0.86      0.86      2022
weighted avg       0.87      0.86      0.86      2022



In [74]:
evaluation_xgbc(model_path='models_joblib/omox_xgbc_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_xgbc_evaluation.json')

Test Set Metrics
Accuracy: 0.8422354104846687
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1703    0]
 [ 319    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.00      0.00      0.00       319

    accuracy                           0.84      2022
   macro avg       0.42      0.50      0.46      2022
weighted avg       0.71      0.84      0.77      2022



In [59]:
from main import evaluation_svc
evaluation_svc(model_path='models_joblib/cip_svc_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_svc_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [75]:
evaluation_svc(model_path='models_joblib/gen_svc_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_svc_evaluation.json')

Test Set Metrics
Accuracy: 0.8580613254203758
Precision: 0.9514767932489452
Recall: 0.7891513560804899
F1 Score: 0.8627450980392156
ROC AUC: 0.8684095802017922
Confusion Matrix: 
[[833  46]
 [241 902]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.78      0.95      0.85       879
           1       0.95      0.79      0.86      1143

    accuracy                           0.86      2022
   macro avg       0.86      0.87      0.86      2022
weighted avg       0.88      0.86      0.86      2022



In [76]:
evaluation_svc(model_path='models_joblib/omox_svc_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_svc_evaluation.json')

Test Set Metrics
Accuracy: 0.8422354104846687
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1703    0]
 [ 319    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.00      0.00      0.00       319

    accuracy                           0.84      2022
   macro avg       0.42      0.50      0.46      2022
weighted avg       0.71      0.84      0.77      2022



In [60]:
from main import evaluation_nb
evaluation_nb(model_path='models_joblib/cip_nb_model.joblib', test_features_data='datasets/cip_test_features.csv', test_labels_data='datasets/cip_test_labels.csv', evaluation_output_path='evaluation_results_json/cip_nb_evaluation.json')

Test Set Metrics
Accuracy: 0.8986152324431256
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1817    0]
 [ 205    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1817
           1       0.00      0.00      0.00       205

    accuracy                           0.90      2022
   macro avg       0.45      0.50      0.47      2022
weighted avg       0.81      0.90      0.85      2022



In [77]:
evaluation_nb(model_path='models_joblib/gen_nb_model.joblib', test_features_data='datasets/gen_test_features.csv', test_labels_data='datasets/gen_test_labels.csv', evaluation_output_path='evaluation_results_json/gen_nb_evaluation.json')

Test Set Metrics
Accuracy: 0.844213649851632
Precision: 0.8723021582733813
Recall: 0.8486439195100612
F1 Score: 0.8603104212860311
ROC AUC: 0.8435483533841546
Confusion Matrix: 
[[737 142]
 [173 970]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       879
           1       0.87      0.85      0.86      1143

    accuracy                           0.84      2022
   macro avg       0.84      0.84      0.84      2022
weighted avg       0.85      0.84      0.84      2022



In [78]:
evaluation_nb(model_path='models_joblib/omox_nb_model.joblib', test_features_data='datasets/omox_test_features.csv', test_labels_data='datasets/omox_test_labels.csv', evaluation_output_path='evaluation_results_json/omox_nb_evaluation.json')

Test Set Metrics
Accuracy: 0.8422354104846687
Precision: 0.0
Recall: 0.0
F1 Score: 0.0
ROC AUC: 0.5
Confusion Matrix: 
[[1703    0]
 [ 319    0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.84      1.00      0.91      1703
           1       0.00      0.00      0.00       319

    accuracy                           0.84      2022
   macro avg       0.42      0.50      0.46      2022
weighted avg       0.71      0.84      0.77      2022

